// To Compile
// g++ -Wall $([route]/root-config --libs --cflags) -o top_extractor_all_variables_YS top_extractor_all_variables_YS.C
//
// To run to one file
// ./top_extractor2 [source file]  [destination file]
//
// To run all files in certain directory
// for i in /[route]/*; do ./top_extractor2 $i [route]/$(basename ${i/.root/}); done
//


#ifndef __CINT__
// Include all needed headers here 
#include <iostream>
#include "TFile.h"
#include "TTree.h"
#include <stdio.h>
#include <stdlib.h>
#endif 
using namespace std;

char *source_file_path;
char destination_path[1000];
char destination_path_variables[1000];


void top_extractor_all_variables_YS() {
    
    TFile *f = new TFile(source_file_path);
    
    TTree *t = (TTree *) f->Get("TopologicalVariables");
	
	Double_t Centrality_AllJets; t->SetBranchAddress("Centrality_AllJets", &Centrality_AllJets);
	Double_t Cos_Jet1AllJets_AllJets; t->SetBranchAddress("Cos_Jet1AllJets_AllJets", &Cos_Jet1AllJets_AllJets);
	Double_t Cos_Jet1Lepton_Lab; t->SetBranchAddress("Cos_Jet1Lepton_Lab", &Cos_Jet1Lepton_Lab);
	Double_t Cos_Jet2AllJets_AllJets; t->SetBranchAddress("Cos_Jet2AllJets_AllJets", &Cos_Jet2AllJets_AllJets);
	Double_t Cos_Jet2Lepton_Lab; t->SetBranchAddress("Cos_Jet2Lepton_Lab", &Cos_Jet2Lepton_Lab);
	Double_t Cos_LightQuarkJetLepton_BTaggedTop; t->SetBranchAddress("Cos_LightQuarkJetLepton_BTaggedTop", &Cos_LightQuarkJetLepton_BTaggedTop);
	Double_t DeltaPhiJet1Jet2; t->SetBranchAddress("DeltaPhiJet1Jet2", &DeltaPhiJet1Jet2);
	Double_t DeltaPhiJet1MET; t->SetBranchAddress("DeltaPhiJet1MET", &DeltaPhiJet1MET);
	Double_t DeltaPhiJet2MET; t->SetBranchAddress("DeltaPhiJet2MET", &DeltaPhiJet2MET);
	Double_t DeltaPhiLeptonMET; t->SetBranchAddress("DeltaPhiLeptonMET", &DeltaPhiLeptonMET);
	Double_t DeltaRJet1Jet2; t->SetBranchAddress("DeltaRJet1Jet2", &DeltaRJet1Jet2);
	Double_t DeltaRMinLeptonJet; t->SetBranchAddress("DeltaRMinLeptonJet", &DeltaRMinLeptonJet);
	Double_t EventWeight; t->SetBranchAddress("EventWeight", &EventWeight);
	Double_t H_AllJets; t->SetBranchAddress("H_AllJets", &H_AllJets);
	Double_t H_Jet1Jet2; t->SetBranchAddress("H_Jet1Jet2", &H_Jet1Jet2);
	Double_t HT_AllJets; t->SetBranchAddress("HT_AllJets", &HT_AllJets);
	Double_t HT_AllJetsLeptonMET; t->SetBranchAddress("HT_AllJetsLeptonMET", &HT_AllJetsLeptonMET);
	Double_t HT_Jet1Jet2; t->SetBranchAddress("HT_Jet1Jet2", &HT_Jet1Jet2);
	Double_t HT_METlep; t->SetBranchAddress("HT_METlep", &HT_METlep);
	Double_t InstLumi; t->SetBranchAddress("InstLumi", &InstLumi);
	Double_t InvariantMass_AllJets; t->SetBranchAddress("InvariantMass_AllJets", &InvariantMass_AllJets);
	Double_t InvariantMass_Jet1Jet2; t->SetBranchAddress("InvariantMass_Jet1Jet2", &InvariantMass_Jet1Jet2);
	Double_t Jet1MuonPtRel; t->SetBranchAddress("Jet1MuonPtRel", &Jet1MuonPtRel);
	Double_t Jet2MuonPtRel; t->SetBranchAddress("Jet2MuonPtRel", &Jet2MuonPtRel);
	Double_t Jet3MuonPtRel; t->SetBranchAddress("Jet3MuonPtRel", &Jet3MuonPtRel);
	Double_t Jet4MuonPtRel; t->SetBranchAddress("Jet4MuonPtRel", &Jet4MuonPtRel);
	Double_t LeptonDCA; t->SetBranchAddress("LeptonDCA", &LeptonDCA);
	Double_t LeptonDCASig; t->SetBranchAddress("LeptonDCASig", &LeptonDCASig);
	Double_t LeptonDetEta; t->SetBranchAddress("LeptonDetEta", &LeptonDetEta);
	Double_t LeptonDetEtaCFT; t->SetBranchAddress("LeptonDetEtaCFT", &LeptonDetEtaCFT);
	Double_t LeptonE; t->SetBranchAddress("LeptonE", &LeptonE);
	Double_t LeptonEta; t->SetBranchAddress("LeptonEta", &LeptonEta);
	Double_t LeptonPhi; t->SetBranchAddress("LeptonPhi", &LeptonPhi);
	Double_t LeptonPt; t->SetBranchAddress("LeptonPt", &LeptonPt);
	Double_t METPhi; t->SetBranchAddress("METPhi", &METPhi);
	Double_t METPt; t->SetBranchAddress("METPt", &METPt);
	Double_t METPx; t->SetBranchAddress("METPx", &METPx);
	Double_t METPy; t->SetBranchAddress("METPy", &METPy);
	Double_t MetSig; t->SetBranchAddress("MetSig", &MetSig);
	Double_t Pt_Jet1Jet2; t->SetBranchAddress("Pt_Jet1Jet2", &Pt_Jet1Jet2);
	Double_t PVz; t->SetBranchAddress("PVz", &PVz);
	Double_t QTimesEta; t->SetBranchAddress("QTimesEta", &QTimesEta);
	Double_t TransverseMass_Jet1Jet2; t->SetBranchAddress("TransverseMass_Jet1Jet2", &TransverseMass_Jet1Jet2);
	Double_t weight_btag; t->SetBranchAddress("weight_btag", &weight_btag);
	Double_t weight_btagSF; t->SetBranchAddress("weight_btagSF", &weight_btagSF);
	Double_t weight_btagTaga; t->SetBranchAddress("weight_btagTaga", &weight_btagTaga);
	Double_t weight_Lumi; t->SetBranchAddress("weight_Lumi", &weight_Lumi);
	Double_t weight_Lumi2; t->SetBranchAddress("weight_Lumi2", &weight_Lumi2);
	Double_t weight_LeptonDetEta; t->SetBranchAddress("weight_LeptonDetEta", &weight_LeptonDetEta);
	Double_t weight_WPt; t->SetBranchAddress("weight_WPt", &weight_WPt);
	Double_t weight_VJets; t->SetBranchAddress("weight_VJets", &weight_VJets);
	Double_t weight_QCDshape; t->SetBranchAddress("weight_QCDshape", &weight_QCDshape);
	Double_t scale_HF; t->SetBranchAddress("scale_HF", &scale_HF);
	Double_t scale_MC; t->SetBranchAddress("scale_MC", &scale_MC);
	Double_t scale_MC2; t->SetBranchAddress("scale_MC2", &scale_MC2);
	Double_t scale_norm; t->SetBranchAddress("scale_norm", &scale_norm);
	Double_t weight_EMcorr; t->SetBranchAddress("weight_EMcorr", &weight_EMcorr);
	Double_t weight_Muon_ID; t->SetBranchAddress("weight_Muon_ID", &weight_Muon_ID);
	Double_t WPt; t->SetBranchAddress("WPt", &WPt);
	Double_t WTransverseMass; t->SetBranchAddress("WTransverseMass", &WTransverseMass);
	Double_t KS_LeptonPt; t->SetBranchAddress("KS_LeptonPt", &KS_LeptonPt);
	Double_t KS_METPt; t->SetBranchAddress("KS_METPt", &KS_METPt);
	Double_t KS_WTransverseMass; t->SetBranchAddress("KS_WTransverseMass", &KS_WTransverseMass);
	Double_t TrackQPt; t->SetBranchAddress("TrackQPt", &TrackQPt);
	Double_t TrackCurvSig; t->SetBranchAddress("TrackCurvSig", &TrackCurvSig);
	Double_t w_superOR_trig; t->SetBranchAddress("w_superOR_trig", &w_superOR_trig);
	Double_t w_singlelep_trig; t->SetBranchAddress("w_singlelep_trig", &w_singlelep_trig);
	Double_t w_ljets_trig; t->SetBranchAddress("w_ljets_trig", &w_ljets_trig);
	Double_t NuPz_S1; t->SetBranchAddress("NuPz_S1", &NuPz_S1);
	Double_t NuPz_S2; t->SetBranchAddress("NuPz_S2", &NuPz_S2);
	Double_t TopMassMinChiSqr; t->SetBranchAddress("TopMassMinChiSqr", &TopMassMinChiSqr);
	Double_t TopMassMinSig; t->SetBranchAddress("TopMassMinSig", &TopMassMinSig);
	Double_t SigTopMass; t->SetBranchAddress("SigTopMass", &SigTopMass);
	Double_t ChiTopMass; t->SetBranchAddress("ChiTopMass", &ChiTopMass);
	Int_t Is_W1c; t->SetBranchAddress("Is_W1c", &Is_W1c);
	Int_t Analysis; t->SetBranchAddress("Analysis", &Analysis);
	Int_t EventNumber; t->SetBranchAddress("EventNumber", &EventNumber);
	Int_t MCindex; t->SetBranchAddress("MCindex", &MCindex);
	Int_t FiredLepJetsTrigger; t->SetBranchAddress("FiredLepJetsTrigger", &FiredLepJetsTrigger);
	Int_t FiredSingleLepTrigger; t->SetBranchAddress("FiredSingleLepTrigger", &FiredSingleLepTrigger);
	Int_t Jet1MuonTagCharge; t->SetBranchAddress("Jet1MuonTagCharge", &Jet1MuonTagCharge);
	Int_t Jet1PartonMatch; t->SetBranchAddress("Jet1PartonMatch", &Jet1PartonMatch);
	Int_t Jet2MuonTagCharge; t->SetBranchAddress("Jet2MuonTagCharge", &Jet2MuonTagCharge);
	Int_t Jet2PartonMatch; t->SetBranchAddress("Jet2PartonMatch", &Jet2PartonMatch);
	Int_t Jet3MuonTagCharge; t->SetBranchAddress("Jet3MuonTagCharge", &Jet3MuonTagCharge);
	Int_t Jet3PartonMatch; t->SetBranchAddress("Jet3PartonMatch", &Jet3PartonMatch);
	Int_t Jet4MuonTagCharge; t->SetBranchAddress("Jet4MuonTagCharge", &Jet4MuonTagCharge);
	Int_t Jet4PartonMatch; t->SetBranchAddress("Jet4PartonMatch", &Jet4PartonMatch);
	Int_t LeptonCharge; t->SetBranchAddress("LeptonCharge", &LeptonCharge);
	Int_t LeptonNCFTHits; t->SetBranchAddress("LeptonNCFTHits", &LeptonNCFTHits);
	Int_t LeptonNSMTHits; t->SetBranchAddress("LeptonNSMTHits", &LeptonNSMTHits);
	Int_t NGoodJets; t->SetBranchAddress("NGoodJets", &NGoodJets);
	Int_t NAllPrimaryVertex; t->SetBranchAddress("NAllPrimaryVertex", &NAllPrimaryVertex);
	Int_t NTaggedJets; t->SetBranchAddress("NTaggedJets", &NTaggedJets);
	Int_t RunNumber; t->SetBranchAddress("RunNumber", &RunNumber);
	Double_t Jet1E; t->SetBranchAddress("Jet1E", &Jet1E);
	Double_t Jet1Pt; t->SetBranchAddress("Jet1Pt", &Jet1Pt);
	Double_t Jet1Phi; t->SetBranchAddress("Jet1Phi", &Jet1Phi);
	Double_t Jet1Eta; t->SetBranchAddress("Jet1Eta", &Jet1Eta);
	Double_t Jet1DetEta; t->SetBranchAddress("Jet1DetEta", &Jet1DetEta);
	Double_t Jet1Mass; t->SetBranchAddress("Jet1Mass", &Jet1Mass);
	Double_t Jet1BTagNN; t->SetBranchAddress("Jet1BTagNN", &Jet1BTagNN);
	Double_t Jet1LeptonDeltaPhi; t->SetBranchAddress("Jet1LeptonDeltaPhi", &Jet1LeptonDeltaPhi);
	Double_t Jet1LeptonDeltaR; t->SetBranchAddress("Jet1LeptonDeltaR", &Jet1LeptonDeltaR);
	Double_t Jet1QTimesEta; t->SetBranchAddress("Jet1QTimesEta", &Jet1QTimesEta);
	Double_t Jet1Taggability; t->SetBranchAddress("Jet1Taggability", &Jet1Taggability);
	Double_t Jet1Taggability_Error; t->SetBranchAddress("Jet1Taggability_Error", &Jet1Taggability_Error);
	Int_t Jet1HasMU; t->SetBranchAddress("Jet1HasMU", &Jet1HasMU);
	Int_t Jet1Flavor; t->SetBranchAddress("Jet1Flavor", &Jet1Flavor);
	Double_t Jet2E; t->SetBranchAddress("Jet2E", &Jet2E);
	Double_t Jet2Pt; t->SetBranchAddress("Jet2Pt", &Jet2Pt);
	Double_t Jet2Phi; t->SetBranchAddress("Jet2Phi", &Jet2Phi);
	Double_t Jet2Eta; t->SetBranchAddress("Jet2Eta", &Jet2Eta);
	Double_t Jet2DetEta; t->SetBranchAddress("Jet2DetEta", &Jet2DetEta);
	Double_t Jet2Mass; t->SetBranchAddress("Jet2Mass", &Jet2Mass);
	Double_t Jet2BTagNN; t->SetBranchAddress("Jet2BTagNN", &Jet2BTagNN);
	Double_t Jet2LeptonDeltaPhi; t->SetBranchAddress("Jet2LeptonDeltaPhi", &Jet2LeptonDeltaPhi);
	Double_t Jet2LeptonDeltaR; t->SetBranchAddress("Jet2LeptonDeltaR", &Jet2LeptonDeltaR);
	Double_t Jet2QTimesEta; t->SetBranchAddress("Jet2QTimesEta", &Jet2QTimesEta);
	Double_t Jet2Taggability; t->SetBranchAddress("Jet2Taggability", &Jet2Taggability);
	Double_t Jet2Taggability_Error; t->SetBranchAddress("Jet2Taggability_Error", &Jet2Taggability_Error);
	Int_t Jet2HasMU; t->SetBranchAddress("Jet2HasMU", &Jet2HasMU);
	Int_t Jet2Flavor; t->SetBranchAddress("Jet2Flavor", &Jet2Flavor);
	Double_t Jet3E; t->SetBranchAddress("Jet3E", &Jet3E);
	Double_t Jet3Pt; t->SetBranchAddress("Jet3Pt", &Jet3Pt);
	Double_t Jet3Phi; t->SetBranchAddress("Jet3Phi", &Jet3Phi);
	Double_t Jet3Eta; t->SetBranchAddress("Jet3Eta", &Jet3Eta);
	Double_t Jet3DetEta; t->SetBranchAddress("Jet3DetEta", &Jet3DetEta);
	Double_t Jet3Mass; t->SetBranchAddress("Jet3Mass", &Jet3Mass);
	Double_t Jet3BTagNN; t->SetBranchAddress("Jet3BTagNN", &Jet3BTagNN);
	Double_t Jet3LeptonDeltaPhi; t->SetBranchAddress("Jet3LeptonDeltaPhi", &Jet3LeptonDeltaPhi);
	Double_t Jet3LeptonDeltaR; t->SetBranchAddress("Jet3LeptonDeltaR", &Jet3LeptonDeltaR);
	Double_t Jet3QTimesEta; t->SetBranchAddress("Jet3QTimesEta", &Jet3QTimesEta);
	Double_t Jet3Taggability; t->SetBranchAddress("Jet3Taggability", &Jet3Taggability);
	Double_t Jet3Taggability_Error; t->SetBranchAddress("Jet3Taggability_Error", &Jet3Taggability_Error);
	Int_t Jet3HasMU; t->SetBranchAddress("Jet3HasMU", &Jet3HasMU);
	Int_t Jet3Flavor; t->SetBranchAddress("Jet3Flavor", &Jet3Flavor);
	Double_t Jet4E; t->SetBranchAddress("Jet4E", &Jet4E);
	Double_t Jet4Pt; t->SetBranchAddress("Jet4Pt", &Jet4Pt);
	Double_t Jet4Phi; t->SetBranchAddress("Jet4Phi", &Jet4Phi);
	Double_t Jet4Eta; t->SetBranchAddress("Jet4Eta", &Jet4Eta);
	Double_t Jet4DetEta; t->SetBranchAddress("Jet4DetEta", &Jet4DetEta);
	Double_t Jet4Mass; t->SetBranchAddress("Jet4Mass", &Jet4Mass);
	Double_t Jet4BTagNN; t->SetBranchAddress("Jet4BTagNN", &Jet4BTagNN);
	Double_t Jet4LeptonDeltaPhi; t->SetBranchAddress("Jet4LeptonDeltaPhi", &Jet4LeptonDeltaPhi);
	Double_t Jet4LeptonDeltaR; t->SetBranchAddress("Jet4LeptonDeltaR", &Jet4LeptonDeltaR);
	Double_t Jet4QTimesEta; t->SetBranchAddress("Jet4QTimesEta", &Jet4QTimesEta);
	Double_t Jet4Taggability; t->SetBranchAddress("Jet4Taggability", &Jet4Taggability);
	Double_t Jet4Taggability_Error; t->SetBranchAddress("Jet4Taggability_Error", &Jet4Taggability_Error);
	Int_t Jet4HasMU; t->SetBranchAddress("Jet4HasMU", &Jet4HasMU);
	Int_t Jet4Flavor; t->SetBranchAddress("Jet4Flavor", &Jet4Flavor);
	Double_t MostBLikeJetE; t->SetBranchAddress("MostBLikeJetE", &MostBLikeJetE);
	Double_t MostBLikeJetPt; t->SetBranchAddress("MostBLikeJetPt", &MostBLikeJetPt);
	Double_t MostBLikeJetPhi; t->SetBranchAddress("MostBLikeJetPhi", &MostBLikeJetPhi);
	Double_t MostBLikeJetEta; t->SetBranchAddress("MostBLikeJetEta", &MostBLikeJetEta);
	Double_t MostBLikeJetDetEta; t->SetBranchAddress("MostBLikeJetDetEta", &MostBLikeJetDetEta);
	Double_t MostBLikeJetMass; t->SetBranchAddress("MostBLikeJetMass", &MostBLikeJetMass);
	Double_t MostBLikeJetBTagNN; t->SetBranchAddress("MostBLikeJetBTagNN", &MostBLikeJetBTagNN);
	Double_t MostBLikeJetLeptonDeltaPhi; t->SetBranchAddress("MostBLikeJetLeptonDeltaPhi", &MostBLikeJetLeptonDeltaPhi);
	Double_t MostBLikeJetLeptonDeltaR; t->SetBranchAddress("MostBLikeJetLeptonDeltaR", &MostBLikeJetLeptonDeltaR);
	Double_t MostBLikeJetQTimesEta; t->SetBranchAddress("MostBLikeJetQTimesEta", &MostBLikeJetQTimesEta);
	Double_t LeadingBTaggedJetE; t->SetBranchAddress("LeadingBTaggedJetE", &LeadingBTaggedJetE);
	Double_t LeadingBTaggedJetPt; t->SetBranchAddress("LeadingBTaggedJetPt", &LeadingBTaggedJetPt);
	Double_t LeadingBTaggedJetPhi; t->SetBranchAddress("LeadingBTaggedJetPhi", &LeadingBTaggedJetPhi);
	Double_t LeadingBTaggedJetEta; t->SetBranchAddress("LeadingBTaggedJetEta", &LeadingBTaggedJetEta);
	Double_t LeadingBTaggedJetDetEta; t->SetBranchAddress("LeadingBTaggedJetDetEta", &LeadingBTaggedJetDetEta);
	Double_t LeadingBTaggedJetMass; t->SetBranchAddress("LeadingBTaggedJetMass", &LeadingBTaggedJetMass);
	Double_t LeadingBTaggedJetBTagNN; t->SetBranchAddress("LeadingBTaggedJetBTagNN", &LeadingBTaggedJetBTagNN);
	Double_t LeadingBTaggedJetLeptonDeltaPhi; t->SetBranchAddress("LeadingBTaggedJetLeptonDeltaPhi", &LeadingBTaggedJetLeptonDeltaPhi);
	Double_t LeadingBTaggedJetLeptonDeltaR; t->SetBranchAddress("LeadingBTaggedJetLeptonDeltaR", &LeadingBTaggedJetLeptonDeltaR);
	Double_t LeadingBTaggedJetQTimesEta; t->SetBranchAddress("LeadingBTaggedJetQTimesEta", &LeadingBTaggedJetQTimesEta);
	Double_t SecondBTaggedJetE; t->SetBranchAddress("SecondBTaggedJetE", &SecondBTaggedJetE);
	Double_t SecondBTaggedJetPt; t->SetBranchAddress("SecondBTaggedJetPt", &SecondBTaggedJetPt);
	Double_t SecondBTaggedJetPhi; t->SetBranchAddress("SecondBTaggedJetPhi", &SecondBTaggedJetPhi);
	Double_t SecondBTaggedJetEta; t->SetBranchAddress("SecondBTaggedJetEta", &SecondBTaggedJetEta);
	Double_t SecondBTaggedJetDetEta; t->SetBranchAddress("SecondBTaggedJetDetEta", &SecondBTaggedJetDetEta);
	Double_t SecondBTaggedJetMass; t->SetBranchAddress("SecondBTaggedJetMass", &SecondBTaggedJetMass);
	Double_t SecondBTaggedJetBTagNN; t->SetBranchAddress("SecondBTaggedJetBTagNN", &SecondBTaggedJetBTagNN);
	Double_t SecondBTaggedJetLeptonDeltaPhi; t->SetBranchAddress("SecondBTaggedJetLeptonDeltaPhi", &SecondBTaggedJetLeptonDeltaPhi);
	Double_t SecondBTaggedJetLeptonDeltaR; t->SetBranchAddress("SecondBTaggedJetLeptonDeltaR", &SecondBTaggedJetLeptonDeltaR);
	Double_t SecondBTaggedJetQTimesEta; t->SetBranchAddress("SecondBTaggedJetQTimesEta", &SecondBTaggedJetQTimesEta);
	Double_t LeadingLightQuarkJetE; t->SetBranchAddress("LeadingLightQuarkJetE", &LeadingLightQuarkJetE);
	Double_t LeadingLightQuarkJetPt; t->SetBranchAddress("LeadingLightQuarkJetPt", &LeadingLightQuarkJetPt);
	Double_t LeadingLightQuarkJetPhi; t->SetBranchAddress("LeadingLightQuarkJetPhi", &LeadingLightQuarkJetPhi);
	Double_t LeadingLightQuarkJetEta; t->SetBranchAddress("LeadingLightQuarkJetEta", &LeadingLightQuarkJetEta);
	Double_t LeadingLightQuarkJetDetEta; t->SetBranchAddress("LeadingLightQuarkJetDetEta", &LeadingLightQuarkJetDetEta);
	Double_t LeadingLightQuarkJetMass; t->SetBranchAddress("LeadingLightQuarkJetMass", &LeadingLightQuarkJetMass);
	Double_t LeadingLightQuarkJetBTagNN; t->SetBranchAddress("LeadingLightQuarkJetBTagNN", &LeadingLightQuarkJetBTagNN);
	Double_t LeadingLightQuarkJetLeptonDeltaPhi; t->SetBranchAddress("LeadingLightQuarkJetLeptonDeltaPhi", &LeadingLightQuarkJetLeptonDeltaPhi);
	Double_t LeadingLightQuarkJetLeptonDeltaR; t->SetBranchAddress("LeadingLightQuarkJetLeptonDeltaR", &LeadingLightQuarkJetLeptonDeltaR);
	Double_t LeadingLightQuarkJetQTimesEta; t->SetBranchAddress("LeadingLightQuarkJetQTimesEta", &LeadingLightQuarkJetQTimesEta);
	Double_t SecondLightQuarkJetE; t->SetBranchAddress("SecondLightQuarkJetE", &SecondLightQuarkJetE);
	Double_t SecondLightQuarkJetPt; t->SetBranchAddress("SecondLightQuarkJetPt", &SecondLightQuarkJetPt);
	Double_t SecondLightQuarkJetPhi; t->SetBranchAddress("SecondLightQuarkJetPhi", &SecondLightQuarkJetPhi);
	Double_t SecondLightQuarkJetEta; t->SetBranchAddress("SecondLightQuarkJetEta", &SecondLightQuarkJetEta);
	Double_t SecondLightQuarkJetDetEta; t->SetBranchAddress("SecondLightQuarkJetDetEta", &SecondLightQuarkJetDetEta);
	Double_t SecondLightQuarkJetMass; t->SetBranchAddress("SecondLightQuarkJetMass", &SecondLightQuarkJetMass);
	Double_t SecondLightQuarkJetBTagNN; t->SetBranchAddress("SecondLightQuarkJetBTagNN", &SecondLightQuarkJetBTagNN);
	Double_t SecondLightQuarkJetLeptonDeltaPhi; t->SetBranchAddress("SecondLightQuarkJetLeptonDeltaPhi", &SecondLightQuarkJetLeptonDeltaPhi);
	Double_t SecondLightQuarkJetLeptonDeltaR; t->SetBranchAddress("SecondLightQuarkJetLeptonDeltaR", &SecondLightQuarkJetLeptonDeltaR);
	Double_t SecondLightQuarkJetQTimesEta; t->SetBranchAddress("SecondLightQuarkJetQTimesEta", &SecondLightQuarkJetQTimesEta);
	//Int_t MCkeylength; t->SetBranchAddress("MCkeylength", &MCkeylength);
	//Char_t MCkey[MCkeylength]; t->SetBranchAddress("MCkey[MCkeylength]", &MCkey[MCkeylength]);
	Double_t MEDisc_tb; t->SetBranchAddress("MEDisc_tb", &MEDisc_tb);
	Double_t MEDisc_tqb; t->SetBranchAddress("MEDisc_tqb", &MEDisc_tqb);
	Double_t MEDisc_tbtqb; t->SetBranchAddress("MEDisc_tbtqb", &MEDisc_tbtqb);
	Double_t MEDisc_eq_tbtqb; t->SetBranchAddress("MEDisc_eq_tbtqb", &MEDisc_eq_tbtqb);
	Double_t MEBtagDisc_tb; t->SetBranchAddress("MEBtagDisc_tb", &MEBtagDisc_tb);
	Double_t MEBtagDisc_tqb; t->SetBranchAddress("MEBtagDisc_tqb", &MEBtagDisc_tqb);
	Double_t MEBtagDisc_tbtqb; t->SetBranchAddress("MEBtagDisc_tbtqb", &MEBtagDisc_tbtqb);
	Double_t MEBtagDisc_eq_tbtqb; t->SetBranchAddress("MEBtagDisc_eq_tbtqb", &MEBtagDisc_eq_tbtqb);
	Double_t MEBLBCDisc_tb; t->SetBranchAddress("MEBLBCDisc_tb", &MEBLBCDisc_tb);
	Double_t MEBLBCDisc_tqb; t->SetBranchAddress("MEBLBCDisc_tqb", &MEBLBCDisc_tqb);
	Double_t MEBLBCDisc_tbtqb; t->SetBranchAddress("MEBLBCDisc_tbtqb", &MEBLBCDisc_tbtqb);
	Double_t MEBLBCDisc_eq_tbtqb; t->SetBranchAddress("MEBLBCDisc_eq_tbtqb", &MEBLBCDisc_eq_tbtqb);
	Double_t MEBraveDisc_tb; t->SetBranchAddress("MEBraveDisc_tb", &MEBraveDisc_tb);
	Double_t MEBraveDisc_tqb; t->SetBranchAddress("MEBraveDisc_tqb", &MEBraveDisc_tqb);
	Double_t MEBraveDisc_tbtqb; t->SetBranchAddress("MEBraveDisc_tbtqb", &MEBraveDisc_tbtqb);
	Double_t MEBraveDisc_eq_tbtqb; t->SetBranchAddress("MEBraveDisc_eq_tbtqb", &MEBraveDisc_eq_tbtqb);
	Double_t MEBraveBLBCDisc_tb; t->SetBranchAddress("MEBraveBLBCDisc_tb", &MEBraveBLBCDisc_tb);
	Double_t MEBraveBLBCDisc_tqb; t->SetBranchAddress("MEBraveBLBCDisc_tqb", &MEBraveBLBCDisc_tqb);
	Double_t MEBraveBLBCDisc_tbtqb; t->SetBranchAddress("MEBraveBLBCDisc_tbtqb", &MEBraveBLBCDisc_tbtqb);
	Double_t MEBraveBLBCDisc_eq_tbtqb; t->SetBranchAddress("MEBraveBLBCDisc_eq_tbtqb", &MEBraveBLBCDisc_eq_tbtqb);
	Double_t MEEPDisc_tb; t->SetBranchAddress("MEEPDisc_tb", &MEEPDisc_tb);
	Double_t MEEPDisc_tqb; t->SetBranchAddress("MEEPDisc_tqb", &MEEPDisc_tqb);
	Double_t MEEPDisc_tbtqb; t->SetBranchAddress("MEEPDisc_tbtqb", &MEEPDisc_tbtqb);
	Double_t MEEPDisc_eq_tbtqb; t->SetBranchAddress("MEEPDisc_eq_tbtqb", &MEEPDisc_eq_tbtqb);
	Double_t DeltaPhiMinMETJet; t->SetBranchAddress("DeltaPhiMinMETJet", &DeltaPhiMinMETJet);
	Double_t LeptonChisq; t->SetBranchAddress("LeptonChisq", &LeptonChisq);
	Double_t LeptonChisqProb; t->SetBranchAddress("LeptonChisqProb", &LeptonChisqProb);
	Double_t PVx; t->SetBranchAddress("PVx", &PVx);
	Double_t PVy; t->SetBranchAddress("PVy", &PVy);
	Double_t weight_btagBLBCSF; t->SetBranchAddress("weight_btagBLBCSF", &weight_btagBLBCSF);
	Double_t scale_MM; t->SetBranchAddress("scale_MM", &scale_MM);
	Double_t weight_EMcorr_Plus; t->SetBranchAddress("weight_EMcorr_Plus", &weight_EMcorr_Plus);
	Double_t weight_EMcorr_Minus; t->SetBranchAddress("weight_EMcorr_Minus", &weight_EMcorr_Minus);
	Double_t weight_Muon_ID_Plus; t->SetBranchAddress("weight_Muon_ID_Plus", &weight_Muon_ID_Plus);
	Double_t weight_Muon_ID_Minus; t->SetBranchAddress("weight_Muon_ID_Minus", &weight_Muon_ID_Minus);
	Double_t weight_VC; t->SetBranchAddress("weight_VC", &weight_VC);
	Double_t weight_VC_Plus; t->SetBranchAddress("weight_VC_Plus", &weight_VC_Plus);
	Double_t weight_VC_Minus; t->SetBranchAddress("weight_VC_Minus", &weight_VC_Minus);
	Double_t weight_VCTaga; t->SetBranchAddress("weight_VCTaga", &weight_VCTaga);
	Double_t weight_VCTaga_Plus; t->SetBranchAddress("weight_VCTaga_Plus", &weight_VCTaga_Plus);
	Double_t weight_VCTaga_Minus; t->SetBranchAddress("weight_VCTaga_Minus", &weight_VCTaga_Minus);
	Double_t Jet1PtJES; t->SetBranchAddress("Jet1PtJES", &Jet1PtJES);
	Double_t Jet2PtJES; t->SetBranchAddress("Jet2PtJES", &Jet2PtJES);
	Double_t Jet3PtJES; t->SetBranchAddress("Jet3PtJES", &Jet3PtJES);
	Double_t Jet4PtJES; t->SetBranchAddress("Jet4PtJES", &Jet4PtJES);
	Int_t RunPeriod; t->SetBranchAddress("RunPeriod", &RunPeriod);
	Int_t FiredSuperORTrigger; t->SetBranchAddress("FiredSuperORTrigger", &FiredSuperORTrigger);
	Int_t FiredMegaORTrigger; t->SetBranchAddress("FiredMegaORTrigger", &FiredMegaORTrigger);
	Int_t Jet1IsZB; t->SetBranchAddress("Jet1IsZB", &Jet1IsZB);
	Int_t Jet2IsZB; t->SetBranchAddress("Jet2IsZB", &Jet2IsZB);
	Int_t Jet3IsZB; t->SetBranchAddress("Jet3IsZB", &Jet3IsZB);
	Int_t Jet4IsZB; t->SetBranchAddress("Jet4IsZB", &Jet4IsZB);
	Double_t Jet1BTagMVA; t->SetBranchAddress("Jet1BTagMVA", &Jet1BTagMVA);
	Double_t Jet1BTagMVABC; t->SetBranchAddress("Jet1BTagMVABC", &Jet1BTagMVABC);
	Double_t Jet1BTagMVABLBC; t->SetBranchAddress("Jet1BTagMVABLBC", &Jet1BTagMVABLBC);
	Double_t Jet1BTagMVAVBB; t->SetBranchAddress("Jet1BTagMVAVBB", &Jet1BTagMVAVBB);
	Double_t Jet2BTagMVA; t->SetBranchAddress("Jet2BTagMVA", &Jet2BTagMVA);
	Double_t Jet2BTagMVABC; t->SetBranchAddress("Jet2BTagMVABC", &Jet2BTagMVABC);
	Double_t Jet2BTagMVABLBC; t->SetBranchAddress("Jet2BTagMVABLBC", &Jet2BTagMVABLBC);
	Double_t Jet2BTagMVAVBB; t->SetBranchAddress("Jet2BTagMVAVBB", &Jet2BTagMVAVBB);
	Double_t Jet3BTagMVA; t->SetBranchAddress("Jet3BTagMVA", &Jet3BTagMVA);
	Double_t Jet3BTagMVABC; t->SetBranchAddress("Jet3BTagMVABC", &Jet3BTagMVABC);
	Double_t Jet3BTagMVABLBC; t->SetBranchAddress("Jet3BTagMVABLBC", &Jet3BTagMVABLBC);
	Double_t Jet3BTagMVAVBB; t->SetBranchAddress("Jet3BTagMVAVBB", &Jet3BTagMVAVBB);
	Double_t Jet4BTagMVA; t->SetBranchAddress("Jet4BTagMVA", &Jet4BTagMVA);
	Double_t Jet4BTagMVABC; t->SetBranchAddress("Jet4BTagMVABC", &Jet4BTagMVABC);
	Double_t Jet4BTagMVABLBC; t->SetBranchAddress("Jet4BTagMVABLBC", &Jet4BTagMVABLBC);
	Double_t Jet4BTagMVAVBB; t->SetBranchAddress("Jet4BTagMVAVBB", &Jet4BTagMVAVBB);
	Double_t MostBLikeJetBTagMVA; t->SetBranchAddress("MostBLikeJetBTagMVA", &MostBLikeJetBTagMVA);
	Double_t MostBLikeJetBTagMVABC; t->SetBranchAddress("MostBLikeJetBTagMVABC", &MostBLikeJetBTagMVABC);
	Double_t MostBLikeJetBTagMVABLBC; t->SetBranchAddress("MostBLikeJetBTagMVABLBC", &MostBLikeJetBTagMVABLBC);
	Double_t MostBLikeJetBTagMVAVBB; t->SetBranchAddress("MostBLikeJetBTagMVAVBB", &MostBLikeJetBTagMVAVBB);
	Double_t LeadingLightQuarkJetBTagMVA; t->SetBranchAddress("LeadingLightQuarkJetBTagMVA", &LeadingLightQuarkJetBTagMVA);
	Double_t LeadingLightQuarkJetBTagMVABC; t->SetBranchAddress("LeadingLightQuarkJetBTagMVABC", &LeadingLightQuarkJetBTagMVABC);
	Double_t LeadingLightQuarkJetBTagMVABLBC; t->SetBranchAddress("LeadingLightQuarkJetBTagMVABLBC", &LeadingLightQuarkJetBTagMVABLBC);
	Double_t LeadingLightQuarkJetBTagMVAVBB; t->SetBranchAddress("LeadingLightQuarkJetBTagMVAVBB", &LeadingLightQuarkJetBTagMVAVBB);
	Double_t SecondLightQuarkJetBTagMVA; t->SetBranchAddress("SecondLightQuarkJetBTagMVA", &SecondLightQuarkJetBTagMVA);
	Double_t SecondLightQuarkJetBTagMVABC; t->SetBranchAddress("SecondLightQuarkJetBTagMVABC", &SecondLightQuarkJetBTagMVABC);
	Double_t SecondLightQuarkJetBTagMVABLBC; t->SetBranchAddress("SecondLightQuarkJetBTagMVABLBC", &SecondLightQuarkJetBTagMVABLBC);
	Double_t SecondLightQuarkJetBTagMVAVBB; t->SetBranchAddress("SecondLightQuarkJetBTagMVAVBB", &SecondLightQuarkJetBTagMVAVBB);
	Double_t LeadingBTaggedJetBTagMVA; t->SetBranchAddress("LeadingBTaggedJetBTagMVA", &LeadingBTaggedJetBTagMVA);
	Double_t LeadingBTaggedJetBTagMVABC; t->SetBranchAddress("LeadingBTaggedJetBTagMVABC", &LeadingBTaggedJetBTagMVABC);
	Double_t LeadingBTaggedJetBTagMVABLBC; t->SetBranchAddress("LeadingBTaggedJetBTagMVABLBC", &LeadingBTaggedJetBTagMVABLBC);
	Double_t LeadingBTaggedJetBTagMVAVBB; t->SetBranchAddress("LeadingBTaggedJetBTagMVAVBB", &LeadingBTaggedJetBTagMVAVBB);
	Double_t SecondBTaggedJetBTagMVA; t->SetBranchAddress("SecondBTaggedJetBTagMVA", &SecondBTaggedJetBTagMVA);
	Double_t SecondBTaggedJetBTagMVABC; t->SetBranchAddress("SecondBTaggedJetBTagMVABC", &SecondBTaggedJetBTagMVABC);
	Double_t SecondBTaggedJetBTagMVABLBC; t->SetBranchAddress("SecondBTaggedJetBTagMVABLBC", &SecondBTaggedJetBTagMVABLBC);
	Double_t SecondBTaggedJetBTagMVAVBB; t->SetBranchAddress("SecondBTaggedJetBTagMVAVBB", &SecondBTaggedJetBTagMVAVBB);

	Double_t DT_tb_output; t->SetBranchAddress("DT_tb_output", &DT_tb_output);
	Double_t DT_tqb_output; t->SetBranchAddress("DT_tqb_output", &DT_tqb_output);
	Double_t DT_tbtqb_output; t->SetBranchAddress("DT_tbtqb_output", &DT_tbtqb_output);
	Double_t BNN_tb_output; t->SetBranchAddress("BNN_tb_output", &BNN_tb_output);
	Double_t BNN_tqb_output; t->SetBranchAddress("BNN_tqb_output", &BNN_tqb_output);
	Double_t BNN_tbtqb_output; t->SetBranchAddress("BNN_tbtqb_output", &BNN_tbtqb_output);
	Double_t BNNComb_tb_output; t->SetBranchAddress("BNNComb_tb_output", &BNNComb_tb_output);
	Double_t BNNComb_tqb_output; t->SetBranchAddress("BNNComb_tqb_output", &BNNComb_tqb_output);
	Double_t BNNComb_tbtqb_BMED_output; t->SetBranchAddress("BNNComb_tbtqb_BMED_output", &BNNComb_tbtqb_BMED_output);
	Double_t BNNComb_tbtqb_PblMED_output; t->SetBranchAddress("BNNComb_tbtqb_PblMED_output", &BNNComb_tbtqb_PblMED_output);
	Double_t Prob_tb; t->SetBranchAddress("Prob_tb", &Prob_tb);
	Double_t Prob_tq; t->SetBranchAddress("Prob_tq", &Prob_tq);
	Double_t Prob_wbb; t->SetBranchAddress("Prob_wbb", &Prob_wbb);
	Double_t Prob_wcg; t->SetBranchAddress("Prob_wcg", &Prob_wcg);
	Double_t Prob_wgg; t->SetBranchAddress("Prob_wgg", &Prob_wgg);
	Double_t Prob_ww; t->SetBranchAddress("Prob_ww", &Prob_ww);
	Double_t Prob_wz; t->SetBranchAddress("Prob_wz", &Prob_wz);
	Double_t Prob_ljets; t->SetBranchAddress("Prob_ljets", &Prob_ljets);
	Double_t Prob_ggg; t->SetBranchAddress("Prob_ggg", &Prob_ggg);
	Double_t Prob_tbg; t->SetBranchAddress("Prob_tbg", &Prob_tbg);
	Double_t Prob_tqb; t->SetBranchAddress("Prob_tqb", &Prob_tqb);
	Double_t Prob_tqg; t->SetBranchAddress("Prob_tqg", &Prob_tqg);
	Double_t Prob_wbbg; t->SetBranchAddress("Prob_wbbg", &Prob_wbbg);
	Double_t Prob_wugg; t->SetBranchAddress("Prob_wugg", &Prob_wugg);
	Double_t Prob_l3jets; t->SetBranchAddress("Prob_l3jets", &Prob_l3jets);
	Double_t ProbBtag_tb; t->SetBranchAddress("ProbBtag_tb", &ProbBtag_tb);
	Double_t ProbBtag_tq; t->SetBranchAddress("ProbBtag_tq", &ProbBtag_tq);
	Double_t ProbBtag_wbb; t->SetBranchAddress("ProbBtag_wbb", &ProbBtag_wbb);
	Double_t ProbBtag_wcg; t->SetBranchAddress("ProbBtag_wcg", &ProbBtag_wcg);
	Double_t ProbBtag_wgg; t->SetBranchAddress("ProbBtag_wgg", &ProbBtag_wgg);
	Double_t ProbBtag_ww; t->SetBranchAddress("ProbBtag_ww", &ProbBtag_ww);
	Double_t ProbBtag_wz; t->SetBranchAddress("ProbBtag_wz", &ProbBtag_wz);
	Double_t ProbBtag_ljets; t->SetBranchAddress("ProbBtag_ljets", &ProbBtag_ljets);
	Double_t ProbBtag_ggg; t->SetBranchAddress("ProbBtag_ggg", &ProbBtag_ggg);
	Double_t ProbBtag_tbg; t->SetBranchAddress("ProbBtag_tbg", &ProbBtag_tbg);
	Double_t ProbBtag_tqb; t->SetBranchAddress("ProbBtag_tqb", &ProbBtag_tqb);
	Double_t ProbBtag_tqg; t->SetBranchAddress("ProbBtag_tqg", &ProbBtag_tqg);
	Double_t ProbBtag_wbbg; t->SetBranchAddress("ProbBtag_wbbg", &ProbBtag_wbbg);
	Double_t ProbBtag_wugg; t->SetBranchAddress("ProbBtag_wugg", &ProbBtag_wugg);
	Double_t ProbBtag_l3jets; t->SetBranchAddress("ProbBtag_l3jets", &ProbBtag_l3jets);
	Double_t QTimesLeptonEta; t->SetBranchAddress("QTimesLeptonEta", &QTimesLeptonEta);

    Int_t nevents = t->GetEntries();
    
    FILE *dest_file;
    dest_file = fopen(destination_path,"w");

	// cout << "ok 1";

    for (Int_t i = 0; i<  nevents; i++) {

	t->GetEvent(i);

	fprintf(dest_file,"%30.25f",Centrality_AllJets);
	fprintf(dest_file,"%30.25f",Cos_Jet1AllJets_AllJets);
	fprintf(dest_file,"%30.25f",Cos_Jet1Lepton_Lab);
	fprintf(dest_file,"%30.25f",Cos_Jet2AllJets_AllJets);
	fprintf(dest_file,"%30.25f",Cos_Jet2Lepton_Lab);
	fprintf(dest_file,"%30.25f",Cos_LightQuarkJetLepton_BTaggedTop);
	fprintf(dest_file,"%30.25f",DeltaPhiJet1Jet2);
	fprintf(dest_file,"%30.25f",DeltaPhiJet1MET);
	fprintf(dest_file,"%30.25f",DeltaPhiJet2MET);
	fprintf(dest_file,"%30.25f",DeltaPhiLeptonMET);
	fprintf(dest_file,"%30.25f",DeltaRJet1Jet2);
	fprintf(dest_file,"%30.25f",DeltaRMinLeptonJet);
	//fprintf(dest_file,"%30.25f",EventWeight);
	fprintf(dest_file,"%30.25f",H_AllJets);
	fprintf(dest_file,"%30.25f",H_Jet1Jet2);
	fprintf(dest_file,"%30.25f",HT_AllJets);
	fprintf(dest_file,"%30.25f",HT_AllJetsLeptonMET);
	fprintf(dest_file,"%30.25f",HT_Jet1Jet2);
	fprintf(dest_file,"%30.25f",HT_METlep);
	fprintf(dest_file,"%30.25f",InstLumi);
	fprintf(dest_file,"%30.25f",InvariantMass_AllJets);
	fprintf(dest_file,"%30.25f",InvariantMass_Jet1Jet2);
	fprintf(dest_file,"%30.25f",Jet1MuonPtRel);
	fprintf(dest_file,"%30.25f",Jet2MuonPtRel);
	fprintf(dest_file,"%30.25f",Jet3MuonPtRel);
	fprintf(dest_file,"%30.25f",Jet4MuonPtRel);
	fprintf(dest_file,"%30.25f",LeptonDCA);
	fprintf(dest_file,"%30.25f",LeptonDCASig);
	fprintf(dest_file,"%30.25f",LeptonDetEta);
	fprintf(dest_file,"%30.25f",LeptonDetEtaCFT);
	fprintf(dest_file,"%30.25f",LeptonE);
	fprintf(dest_file,"%30.25f",LeptonEta);
	fprintf(dest_file,"%30.25f",LeptonPhi);
	fprintf(dest_file,"%30.25f",LeptonPt);
	fprintf(dest_file,"%30.25f",METPhi);
	fprintf(dest_file,"%30.25f",METPt);
	fprintf(dest_file,"%30.25f",METPx);
	fprintf(dest_file,"%30.25f",METPy);
	fprintf(dest_file,"%30.25f",MetSig);
	fprintf(dest_file,"%30.25f",Pt_Jet1Jet2);
	fprintf(dest_file,"%30.25f",PVz);
	fprintf(dest_file,"%30.25f",QTimesEta);
	fprintf(dest_file,"%30.25f",TransverseMass_Jet1Jet2);
	fprintf(dest_file,"%30.25f",weight_btag);
	fprintf(dest_file,"%30.25f",weight_btagSF);
	fprintf(dest_file,"%30.25f",weight_btagTaga);
	fprintf(dest_file,"%30.25f",weight_Lumi);
	fprintf(dest_file,"%30.25f",weight_Lumi2);
	fprintf(dest_file,"%30.25f",weight_LeptonDetEta);
	fprintf(dest_file,"%30.25f",weight_WPt);
	fprintf(dest_file,"%30.25f",weight_VJets);
	fprintf(dest_file,"%30.25f",weight_QCDshape);
	fprintf(dest_file,"%30.25f",scale_HF);
	fprintf(dest_file,"%30.25f",scale_MC);
	fprintf(dest_file,"%30.25f",scale_MC2);
	fprintf(dest_file,"%30.25f",scale_norm);
	fprintf(dest_file,"%30.25f",weight_EMcorr);
	fprintf(dest_file,"%30.25f",weight_Muon_ID);
	fprintf(dest_file,"%30.25f",WPt);
	fprintf(dest_file,"%30.25f",WTransverseMass);
	fprintf(dest_file,"%30.25f",KS_LeptonPt);
	fprintf(dest_file,"%30.25f",KS_METPt);
	fprintf(dest_file,"%30.25f",KS_WTransverseMass);
	fprintf(dest_file,"%30.25f",TrackQPt);
	fprintf(dest_file,"%30.25f",TrackCurvSig);
	fprintf(dest_file,"%30.25f",w_superOR_trig);
	fprintf(dest_file,"%30.25f",w_singlelep_trig);
	fprintf(dest_file,"%30.25f",w_ljets_trig);
	fprintf(dest_file,"%30.25f",NuPz_S1);
	fprintf(dest_file,"%30.25f",NuPz_S2);
	fprintf(dest_file,"%30.25f",TopMassMinChiSqr);
	fprintf(dest_file,"%30.25f",TopMassMinSig);
	fprintf(dest_file,"%30.25f",SigTopMass);
	fprintf(dest_file,"%30.25f",ChiTopMass);
	fprintf(dest_file,"%30i",Is_W1c);
	fprintf(dest_file,"%30i",Analysis);
	fprintf(dest_file,"%30i",EventNumber);
	fprintf(dest_file,"%30i",MCindex);
	fprintf(dest_file,"%30i",FiredLepJetsTrigger);
	fprintf(dest_file,"%30i",FiredSingleLepTrigger);
	fprintf(dest_file,"%30i",Jet1MuonTagCharge);
	fprintf(dest_file,"%30i",Jet1PartonMatch);
	fprintf(dest_file,"%30i",Jet2MuonTagCharge);
	fprintf(dest_file,"%30i",Jet2PartonMatch);
	fprintf(dest_file,"%30i",Jet3MuonTagCharge);
	fprintf(dest_file,"%30i",Jet3PartonMatch);
	fprintf(dest_file,"%30i",Jet4MuonTagCharge);
	fprintf(dest_file,"%30i",Jet4PartonMatch);
	fprintf(dest_file,"%30i",LeptonCharge);
	fprintf(dest_file,"%30i",LeptonNCFTHits);
	fprintf(dest_file,"%30i",LeptonNSMTHits);
	fprintf(dest_file,"%30i",NGoodJets);
	fprintf(dest_file,"%30i",NAllPrimaryVertex);
	fprintf(dest_file,"%30i",NTaggedJets);
	fprintf(dest_file,"%30i",RunNumber);
	fprintf(dest_file,"%30.25f",Jet1E);
	fprintf(dest_file,"%30.25f",Jet1Pt);
	fprintf(dest_file,"%30.25f",Jet1Phi);
	fprintf(dest_file,"%30.25f",Jet1Eta);
	fprintf(dest_file,"%30.25f",Jet1DetEta);
	fprintf(dest_file,"%30.25f",Jet1Mass);
	fprintf(dest_file,"%30.25f",Jet1BTagNN);
	fprintf(dest_file,"%30.25f",Jet1LeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",Jet1LeptonDeltaR);
	fprintf(dest_file,"%30.25f",Jet1QTimesEta);
	fprintf(dest_file,"%30.25f",Jet1Taggability);
	fprintf(dest_file,"%30.25f",Jet1Taggability_Error);
	fprintf(dest_file,"%30i",Jet1HasMU);
	fprintf(dest_file,"%30i",Jet1Flavor);
	fprintf(dest_file,"%30.25f",Jet2E);
	fprintf(dest_file,"%30.25f",Jet2Pt);
	fprintf(dest_file,"%30.25f",Jet2Phi);
	fprintf(dest_file,"%30.25f",Jet2Eta);
	fprintf(dest_file,"%30.25f",Jet2DetEta);
	fprintf(dest_file,"%30.25f",Jet2Mass);
	fprintf(dest_file,"%30.25f",Jet2BTagNN);
	fprintf(dest_file,"%30.25f",Jet2LeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",Jet2LeptonDeltaR);
	fprintf(dest_file,"%30.25f",Jet2QTimesEta);
	fprintf(dest_file,"%30.25f",Jet2Taggability);
	fprintf(dest_file,"%30.25f",Jet2Taggability_Error);
	fprintf(dest_file,"%30i",Jet2HasMU);
	fprintf(dest_file,"%30i",Jet2Flavor);
	fprintf(dest_file,"%30.25f",Jet3E);
	fprintf(dest_file,"%30.25f",Jet3Pt);
	fprintf(dest_file,"%30.25f",Jet3Phi);
	fprintf(dest_file,"%30.25f",Jet3Eta);
	fprintf(dest_file,"%30.25f",Jet3DetEta);
	fprintf(dest_file,"%30.25f",Jet3Mass);
	fprintf(dest_file,"%30.25f",Jet3BTagNN);
	fprintf(dest_file,"%30.25f",Jet3LeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",Jet3LeptonDeltaR);
	fprintf(dest_file,"%30.25f",Jet3QTimesEta);
	fprintf(dest_file,"%30.25f",Jet3Taggability);
	fprintf(dest_file,"%30.25f",Jet3Taggability_Error);
	fprintf(dest_file,"%30i",Jet3HasMU);
	fprintf(dest_file,"%30i",Jet3Flavor);
	fprintf(dest_file,"%30.25f",Jet4E);
	fprintf(dest_file,"%30.25f",Jet4Pt);
	fprintf(dest_file,"%30.25f",Jet4Phi);
	fprintf(dest_file,"%30.25f",Jet4Eta);
	fprintf(dest_file,"%30.25f",Jet4DetEta);
	fprintf(dest_file,"%30.25f",Jet4Mass);
	fprintf(dest_file,"%30.25f",Jet4BTagNN);
	fprintf(dest_file,"%30.25f",Jet4LeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",Jet4LeptonDeltaR);
	fprintf(dest_file,"%30.25f",Jet4QTimesEta);
	fprintf(dest_file,"%30.25f",Jet4Taggability);
	fprintf(dest_file,"%30.25f",Jet4Taggability_Error);
	fprintf(dest_file,"%30i",Jet4HasMU);
	fprintf(dest_file,"%30i",Jet4Flavor);
	fprintf(dest_file,"%30.25f",MostBLikeJetE);
	fprintf(dest_file,"%30.25f",MostBLikeJetPt);
	fprintf(dest_file,"%30.25f",MostBLikeJetPhi);
	fprintf(dest_file,"%30.25f",MostBLikeJetEta);
	fprintf(dest_file,"%30.25f",MostBLikeJetDetEta);
	fprintf(dest_file,"%30.25f",MostBLikeJetMass);
	fprintf(dest_file,"%30.25f",MostBLikeJetBTagNN);
	fprintf(dest_file,"%30.25f",MostBLikeJetLeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",MostBLikeJetLeptonDeltaR);
	fprintf(dest_file,"%30.25f",MostBLikeJetQTimesEta);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetE);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetPt);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetPhi);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetEta);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetDetEta);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetMass);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetBTagNN);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetLeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetLeptonDeltaR);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetQTimesEta);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetE);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetPt);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetPhi);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetEta);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetDetEta);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetMass);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetBTagNN);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetLeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetLeptonDeltaR);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetQTimesEta);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetE);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetPt);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetPhi);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetEta);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetDetEta);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetMass);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetBTagNN);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetLeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetLeptonDeltaR);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetQTimesEta);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetE);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetPt);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetPhi);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetEta);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetDetEta);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetMass);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetBTagNN);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetLeptonDeltaPhi);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetLeptonDeltaR);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetQTimesEta);
	//fprintf(dest_file,"%30i",MCkeylength);
	//fprintf(dest_file,"%30s",MCkey[MCkeylength]);
	fprintf(dest_file,"%30.25f",MEDisc_tb);
	fprintf(dest_file,"%30.25f",MEDisc_tqb);
	fprintf(dest_file,"%30.25f",MEDisc_tbtqb);
	fprintf(dest_file,"%30.25f",MEDisc_eq_tbtqb);
	fprintf(dest_file,"%30.25f",MEBtagDisc_tb);
	fprintf(dest_file,"%30.25f",MEBtagDisc_tqb);
	fprintf(dest_file,"%30.25f",MEBtagDisc_tbtqb);
	fprintf(dest_file,"%30.25f",MEBtagDisc_eq_tbtqb);
	fprintf(dest_file,"%30.25f",MEBLBCDisc_tb);
	fprintf(dest_file,"%30.25f",MEBLBCDisc_tqb);
	fprintf(dest_file,"%30.25f",MEBLBCDisc_tbtqb);
	fprintf(dest_file,"%30.25f",MEBLBCDisc_eq_tbtqb);
	fprintf(dest_file,"%30.25f",MEBraveDisc_tb);
	fprintf(dest_file,"%30.25f",MEBraveDisc_tqb);
	fprintf(dest_file,"%30.25f",MEBraveDisc_tbtqb);
	fprintf(dest_file,"%30.25f",MEBraveDisc_eq_tbtqb);
	fprintf(dest_file,"%30.25f",MEBraveBLBCDisc_tb);
	fprintf(dest_file,"%30.25f",MEBraveBLBCDisc_tqb);
	fprintf(dest_file,"%30.25f",MEBraveBLBCDisc_tbtqb);
	fprintf(dest_file,"%30.25f",MEBraveBLBCDisc_eq_tbtqb);
	fprintf(dest_file,"%30.25f",MEEPDisc_tb);
	fprintf(dest_file,"%30.25f",MEEPDisc_tqb);
	fprintf(dest_file,"%30.25f",MEEPDisc_tbtqb);
	fprintf(dest_file,"%30.25f",MEEPDisc_eq_tbtqb);
	fprintf(dest_file,"%30.25f",DeltaPhiMinMETJet);
	fprintf(dest_file,"%30.25f",LeptonChisq);
	fprintf(dest_file,"%30.25f",LeptonChisqProb);
	fprintf(dest_file,"%30.25f",PVx);
	fprintf(dest_file,"%30.25f",PVy);
	fprintf(dest_file,"%30.25f",weight_btagBLBCSF);
	fprintf(dest_file,"%30.25f",scale_MM);
	fprintf(dest_file,"%30.25f",weight_EMcorr_Plus);
	fprintf(dest_file,"%30.25f",weight_EMcorr_Minus);
	fprintf(dest_file,"%30.25f",weight_Muon_ID_Plus);
	fprintf(dest_file,"%30.25f",weight_Muon_ID_Minus);
	fprintf(dest_file,"%30.25f",weight_VC);
	fprintf(dest_file,"%30.25f",weight_VC_Plus);
	fprintf(dest_file,"%30.25f",weight_VC_Minus);
	fprintf(dest_file,"%30.25f",weight_VCTaga);
	fprintf(dest_file,"%30.25f",weight_VCTaga_Plus);
	fprintf(dest_file,"%30.25f",weight_VCTaga_Minus);
	fprintf(dest_file,"%30.25f",Jet1PtJES);
	fprintf(dest_file,"%30.25f",Jet2PtJES);
	fprintf(dest_file,"%30.25f",Jet3PtJES);
	fprintf(dest_file,"%30.25f",Jet4PtJES);
	fprintf(dest_file,"%30i",RunPeriod);
	fprintf(dest_file,"%30i",FiredSuperORTrigger);
	fprintf(dest_file,"%30i",FiredMegaORTrigger);
	fprintf(dest_file,"%30i",Jet1IsZB);
	fprintf(dest_file,"%30i",Jet2IsZB);
	fprintf(dest_file,"%30i",Jet3IsZB);
	fprintf(dest_file,"%30i",Jet4IsZB);
	fprintf(dest_file,"%30.25f",Jet1BTagMVA);
	fprintf(dest_file,"%30.25f",Jet1BTagMVABC);
	fprintf(dest_file,"%30.25f",Jet1BTagMVABLBC);
	fprintf(dest_file,"%30.25f",Jet1BTagMVAVBB);
	fprintf(dest_file,"%30.25f",Jet2BTagMVA);
	fprintf(dest_file,"%30.25f",Jet2BTagMVABC);
	fprintf(dest_file,"%30.25f",Jet2BTagMVABLBC);
	fprintf(dest_file,"%30.25f",Jet2BTagMVAVBB);
	fprintf(dest_file,"%30.25f",Jet3BTagMVA);
	fprintf(dest_file,"%30.25f",Jet3BTagMVABC);
	fprintf(dest_file,"%30.25f",Jet3BTagMVABLBC);
	fprintf(dest_file,"%30.25f",Jet3BTagMVAVBB);
	fprintf(dest_file,"%30.25f",Jet4BTagMVA);
	fprintf(dest_file,"%30.25f",Jet4BTagMVABC);
	fprintf(dest_file,"%30.25f",Jet4BTagMVABLBC);
	fprintf(dest_file,"%30.25f",Jet4BTagMVAVBB);
	fprintf(dest_file,"%30.25f",MostBLikeJetBTagMVA);
	fprintf(dest_file,"%30.25f",MostBLikeJetBTagMVABC);
	fprintf(dest_file,"%30.25f",MostBLikeJetBTagMVABLBC);
	fprintf(dest_file,"%30.25f",MostBLikeJetBTagMVAVBB);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetBTagMVA);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetBTagMVABC);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetBTagMVABLBC);
	fprintf(dest_file,"%30.25f",LeadingLightQuarkJetBTagMVAVBB);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetBTagMVA);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetBTagMVABC);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetBTagMVABLBC);
	fprintf(dest_file,"%30.25f",SecondLightQuarkJetBTagMVAVBB);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetBTagMVA);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetBTagMVABC);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetBTagMVABLBC);
	fprintf(dest_file,"%30.25f",LeadingBTaggedJetBTagMVAVBB);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetBTagMVA);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetBTagMVABC);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetBTagMVABLBC);
	fprintf(dest_file,"%30.25f",SecondBTaggedJetBTagMVAVBB);
	//fprintf(dest_file,"%30i",MCkeylength);
	//fprintf(dest_file,"%30s",MCkey[MCkeylength]);
	fprintf(dest_file,"%30.25f",DT_tb_output);
	fprintf(dest_file,"%30.25f",DT_tqb_output);
	fprintf(dest_file,"%30.25f",DT_tbtqb_output);
	fprintf(dest_file,"%30.25f",BNN_tb_output);
	fprintf(dest_file,"%30.25f",BNN_tqb_output);
	fprintf(dest_file,"%30.25f",BNN_tbtqb_output);
	fprintf(dest_file,"%30.25f",BNNComb_tb_output);
	fprintf(dest_file,"%30.25f",BNNComb_tqb_output);
	fprintf(dest_file,"%30.25f",BNNComb_tbtqb_BMED_output);
	fprintf(dest_file,"%30.25f",BNNComb_tbtqb_PblMED_output);
	fprintf(dest_file,"%30.25f",Prob_tb);
	fprintf(dest_file,"%30.25f",Prob_tq);
	fprintf(dest_file,"%30.25f",Prob_wbb);
	fprintf(dest_file,"%30.25f",Prob_wcg);
	fprintf(dest_file,"%30.25f",Prob_wgg);
	fprintf(dest_file,"%30.25f",Prob_ww);
	fprintf(dest_file,"%30.25f",Prob_wz);
	fprintf(dest_file,"%30.25f",Prob_ljets);
	fprintf(dest_file,"%30.25f",Prob_ggg);
	fprintf(dest_file,"%30.25f",Prob_tbg);
	fprintf(dest_file,"%30.25f",Prob_tqb);
	fprintf(dest_file,"%30.25f",Prob_tqg);
	fprintf(dest_file,"%30.25f",Prob_wbbg);
	fprintf(dest_file,"%30.25f",Prob_wugg);
	fprintf(dest_file,"%30.25f",Prob_l3jets);
	fprintf(dest_file,"%30.25f",ProbBtag_tb);
	fprintf(dest_file,"%30.25f",ProbBtag_tq);
	fprintf(dest_file,"%30.25f",ProbBtag_wbb);
	fprintf(dest_file,"%30.25f",ProbBtag_wcg);
	fprintf(dest_file,"%30.25f",ProbBtag_wgg);
	fprintf(dest_file,"%30.25f",ProbBtag_ww);
	fprintf(dest_file,"%30.25f",ProbBtag_wz);
	fprintf(dest_file,"%30.25f",ProbBtag_ljets);
	fprintf(dest_file,"%30.25f",ProbBtag_ggg);
	fprintf(dest_file,"%30.25f",ProbBtag_tbg);
	fprintf(dest_file,"%30.25f",ProbBtag_tqb);
	fprintf(dest_file,"%30.25f",ProbBtag_tqg);
	fprintf(dest_file,"%30.25f",ProbBtag_wbbg);
	fprintf(dest_file,"%30.25f",ProbBtag_wugg);
	fprintf(dest_file,"%30.25f",ProbBtag_l3jets);
	fprintf(dest_file,"%30.25f",QTimesLeptonEta);
	fprintf(dest_file,"%30.25f\n",EventWeight);
    }

    fclose(dest_file);

//  dest_file = fopen(destination_path_variables,"w");    
//
//  TObjArray *arr = t->GetListOfBranches();
//  for (int i = 0; i < arr->GetSize(); i++) {
//      fprintf(dest_file,"%s\n", arr->At(i)->GetTitle() );
//  }
//  fclose(dest_file);

}



#ifndef __CINT__
int main(int argc, char** argv)
{
    source_file_path = argv[1];

    sprintf(destination_path,"%s.txt",argv[2]);
   // sprintf(destination_path_variables,"%s.var_list",argv[2]);

    top_extractor_all_variables_YS();

    return 0;
}
#endif


